### ISSUE TITLE
EIA bug fix needed

### ISSUE THREAD

**Issue by paulinchin** [gemini3d/gemini3d#50]
EIA implementation provides unrealistic wind patterns on a stretched grid and needs to be checked. Can be a problem with specification of winds over various altitudes.

![Screen Shot 2020-11-03 at 8 31 21 AM](https://user-images.githubusercontent.com/12620792/97991144-0547b580-1daf-11eb-88f8-e129e364f79f.png)

**Comment by scivision** [comment]
Is there a particular config.nml from Gemini-examples that reproduces this, or can you upload the config.nml that does this?

**Comment by mattzett** [comment]
I'm pretty sure this is due to the way the code is computing the location of the magnetic equator where it applies the drift values...  I think historically this capability was first implemented when we were only using uniform grids so the equator location (in x1) on a closed grid was basically x%x1(lx1/2).  On a stretched grid this is no longer the case.

**Comment by mattzett** [comment]
```
        z = x%altall(lx1/2,ix2,ix3)  !Current altitude of center of this flux tube
```
This is the problem...

**Comment by mattzett** [comment]
I can put in some code that hopefully fixes this but I'll need @paulinchin to test it on his setup...
